/*
 * Grade Calc
 * Grade Calculator App
 *
 * OpenAPI spec version: 0.0.1
 * Contact: eli.burch@burchbytes.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.36
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ModelClass model module.
 * @module model/ModelClass
 * @version 0.0.1
 */
export class ModelClass {
  /**
   * Constructs a new <code>ModelClass</code>.
   * @alias module:model/ModelClass
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ModelClass</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelClass} obj Optional instance to populate.
   * @return {module:model/ModelClass} The populated <code>ModelClass</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ModelClass();
      if (data.hasOwnProperty('className'))
        obj.className = ApiClient.convertToType(data['className'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} className
 */
ModelClass.prototype.className = undefined;

