/*
 * Grade Calc
 * Grade Calculator App
 *
 * OpenAPI spec version: 0.0.1
 * Contact: eli.burch@burchbytes.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.36
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UserDto model module.
 * @module model/UserDto
 * @version 0.0.1
 */
export class UserDto {
  /**
   * Constructs a new <code>UserDto</code>.
   * @alias module:model/UserDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UserDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserDto} obj Optional instance to populate.
   * @return {module:model/UserDto} The populated <code>UserDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserDto();
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
      if (data.hasOwnProperty('matchingPassword'))
        obj.matchingPassword = ApiClient.convertToType(data['matchingPassword'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} username
 */
UserDto.prototype.username = undefined;

/**
 * @member {String} password
 */
UserDto.prototype.password = undefined;

/**
 * @member {String} matchingPassword
 */
UserDto.prototype.matchingPassword = undefined;

