/*
 * Grade Calc
 * Grade Calculator App
 *
 * OpenAPI spec version: 0.0.1
 * Contact: eli.burch@burchbytes.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.36
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GradeCalc);
  }
}(this, function(expect, GradeCalc) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('UserDto', function() {
      beforeEach(function() {
        instance = new GradeCalc.UserDto();
      });

      it('should create an instance of UserDto', function() {
        // TODO: update the code to test UserDto
        expect(instance).to.be.a(GradeCalc.UserDto);
      });

      it('should have the property username (base name: "username")', function() {
        // TODO: update the code to test the property username
        expect(instance).to.have.property('username');
        // expect(instance.username).to.be(expectedValueLiteral);
      });

      it('should have the property password (base name: "password")', function() {
        // TODO: update the code to test the property password
        expect(instance).to.have.property('password');
        // expect(instance.password).to.be(expectedValueLiteral);
      });

      it('should have the property matchingPassword (base name: "matchingPassword")', function() {
        // TODO: update the code to test the property matchingPassword
        expect(instance).to.have.property('matchingPassword');
        // expect(instance.matchingPassword).to.be(expectedValueLiteral);
      });

    });
  });

}));
