/*
 * Grade Calc
 * Grade Calculator App
 *
 * OpenAPI spec version: 0.0.1
 * Contact: eli.burch@burchbytes.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.36
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {AssignmentDto} from './model/AssignmentDto';
import {GradeResponse} from './model/GradeResponse';
import {ModelClass} from './model/ModelClass';
import {UserDto} from './model/UserDto';
import {AssignmentControllerApi} from './api/AssignmentControllerApi';
import {ClassControllerApi} from './api/ClassControllerApi';
import {GradeControllerApi} from './api/GradeControllerApi';
import {RegisterControllerApi} from './api/RegisterControllerApi';

/**
* Grade_Calculator_App.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var GradeCalc = require('index'); // See note below*.
* var xxxSvc = new GradeCalc.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new GradeCalc.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new GradeCalc.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new GradeCalc.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AssignmentDto model constructor.
     * @property {module:model/AssignmentDto}
     */
    AssignmentDto,

    /**
     * The GradeResponse model constructor.
     * @property {module:model/GradeResponse}
     */
    GradeResponse,

    /**
     * The ModelClass model constructor.
     * @property {module:model/ModelClass}
     */
    ModelClass,

    /**
     * The UserDto model constructor.
     * @property {module:model/UserDto}
     */
    UserDto,

    /**
    * The AssignmentControllerApi service constructor.
    * @property {module:api/AssignmentControllerApi}
    */
    AssignmentControllerApi,

    /**
    * The ClassControllerApi service constructor.
    * @property {module:api/ClassControllerApi}
    */
    ClassControllerApi,

    /**
    * The GradeControllerApi service constructor.
    * @property {module:api/GradeControllerApi}
    */
    GradeControllerApi,

    /**
    * The RegisterControllerApi service constructor.
    * @property {module:api/RegisterControllerApi}
    */
    RegisterControllerApi
};
