/*
 * Grade Calc
 * Grade Calculator App
 *
 * OpenAPI spec version: 0.0.1
 * Contact: eli.burch@burchbytes.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.36
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GradeCalc);
  }
}(this, function(expect, GradeCalc) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GradeCalc.AssignmentControllerApi();
  });

  describe('(package)', function() {
    describe('AssignmentControllerApi', function() {
      describe('addAssignmentToClass', function() {
        it('should call addAssignmentToClass successfully', function(done) {
          // TODO: uncomment, update parameter values for addAssignmentToClass call
          /*

          instance.addAssignmentToClass(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAssignmentsByClass', function() {
        it('should call getAssignmentsByClass successfully', function(done) {
          // TODO: uncomment, update parameter values for getAssignmentsByClass call and complete the assertions
          /*

          instance.getAssignmentsByClass(className, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('removeAssignment', function() {
        it('should call removeAssignment successfully', function(done) {
          // TODO: uncomment, update parameter values for removeAssignment call
          /*

          instance.removeAssignment(assignmentName, className, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
