/*
 * Grade Calc
 * Grade Calculator App
 *
 * OpenAPI spec version: 0.0.1
 * Contact: eli.burch@burchbytes.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.36
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GradeCalc);
  }
}(this, function(expect, GradeCalc) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GradeCalc.GradeControllerApi();
  });

  describe('(package)', function() {
    describe('GradeControllerApi', function() {
      describe('computeGrade', function() {
        it('should call computeGrade successfully', function(done) {
          // TODO: uncomment, update parameter values for computeGrade call and complete the assertions
          /*

          instance.computeGrade(className, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(GradeCalc.GradeResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('computeMaxGrade', function() {
        it('should call computeMaxGrade successfully', function(done) {
          // TODO: uncomment, update parameter values for computeMaxGrade call and complete the assertions
          /*

          instance.computeMaxGrade(className, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(GradeCalc.GradeResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('computeRequiredGrade', function() {
        it('should call computeRequiredGrade successfully', function(done) {
          // TODO: uncomment, update parameter values for computeRequiredGrade call and complete the assertions
          /*

          instance.computeRequiredGrade(className, targetGrade, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(GradeCalc.GradeResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
